<?php
return [
    [
        'name' => 'SavedSearch_Methods08',
        'entity' => 'SavedSearch',
        'cleanup' => 'unused',
        'update' => 'unmodified',
        'params' => [
            'version' => 4,
            'values' => [
                'name' => 'Methods08',
                'label' => 'Methods',
                'form_values' => NULL,
                'mapping_id' => NULL,
                'search_custom_id' => NULL,
                'api_entity' => 'RentalsMethod',
                'api_params' => [
                    'version' => 4,
                    'select' => [
                        'id',
                        'name',
                        'created_id.display_name',
                        'created_date',
                        'modified_id',
                        'modified_date',
                    ],
                    'orderBy' => [],
                    'where' => [],
                    'groupBy' => [],
                    'join' => [],
                    'having' => [],
                ],
                'expires_date' => NULL,
                'description' => NULL,
            ],
        ],
    ],
    [
        'name' => 'SavedSearch_Methods08_SearchDisplay_Methods_Table08',
        'entity' => 'SearchDisplay',
        'cleanup' => 'unused',
        'update' => 'unmodified',
        'params' => [
            'version' => 4,
            'values' => [
                'name' => 'Methods_Table08',
                'label' => 'Methods Table',
                'saved_search_id.name' => 'Methods08',
                'type' => 'table',
                'settings' => [
                    'actions' => TRUE,
                    'limit' => 50,
                    'classes' => [
                        'table',
                        'table-striped',
                    ],
                    'pager' => [],
                    'placeholder' => 5,
                    'sort' => [],
                    'columns' => [
                        [
                            'type' => 'field',
                            'key' => 'id',
                            'dataType' => 'Integer',
                            'label' => 'ID',
                            'sortable' => TRUE,
                        ],
                        [
                            'type' => 'field',
                            'key' => 'name',
                            'dataType' => 'String',
                            'label' => 'Name',
                            'sortable' => TRUE,
                            'editable' => TRUE,
                        ],
                        [
                            'type' => 'field',
                            'key' => 'created_id.display_name',
                            'dataType' => 'String',
                            'label' => 'Created By',
                            'sortable' => TRUE,
                        ],
                        [
                            'type' => 'field',
                            'key' => 'created_date',
                            'dataType' => 'Timestamp',
                            'label' => 'Created Date',
                            'sortable' => TRUE,
                        ],
                        [
                            'type' => 'field',
                            'key' => 'modified_id',
                            'dataType' => 'Integer',
                            'label' => 'Modified By',
                            'sortable' => TRUE,
                        ],
                        [
                            'type' => 'field',
                            'key' => 'modified_date',
                            'dataType' => 'Timestamp',
                            'label' => 'Modified Date',
                            'sortable' => TRUE,
                        ],
                        [
                            'links' => [
                                [
                                    'entity' => 'RentalsMethod',
                                    'action' => 'update',
                                    'join' => '',
                                    'target' => 'crm-popup',
                                    'icon' => 'fa-pencil',
                                    'text' => 'View/Edit Rentals',
                                    'style' => 'default',
                                    'path' => '',
                                    'condition' => [],
                                ],
                            ],
                            'type' => 'links',
                            'alignment' => 'text-right',
                            'label' => 'Actions',
                        ],
                    ],
                ],
                'acl_bypass' => FALSE,
            ],
        ],
    ],
];