<?php
return [
    [
        'name' => 'SavedSearch_Payments08',
        'entity' => 'SavedSearch',
        'cleanup' => 'unused',
        'update' => 'unmodified',
        'params' => [
            'version' => 4,
            'values' => [
                'name' => 'Payments08',
                'label' => 'Search Payments',
                'form_values' => NULL,
                'mapping_id' => NULL,
                'search_custom_id' => NULL,
                'api_entity' => 'RentalsPayment',
                'api_params' => [
                    'version' => 4,
                    'select' => [
                        'id',
                        'code',
                        'RentalsPayment_Contact_tenant_id_01.display_name',
                        'RentalsPayment_RentalsMethod_method_id_01.name',
                        'amount',
                        'created_id.display_name',
                        'created_date',
                        'modified_id.display_name',
                        'modified_date',
                    ],
                    'orderBy' => [],
                    'where' => [['RentalsPayment_Contact_tenant_id_01.is_deleted',
                        '<>',
                        1]],
                    'groupBy' => [],
                    'join' => [
                        [
                            'Contact AS RentalsPayment_Contact_tenant_id_01',
                            'LEFT',
                            [
                                'tenant_id',
                                '=',
                                'RentalsPayment_Contact_tenant_id_01.id',
                            ],
                        ],
                        [
                            'RentalsMethod AS RentalsPayment_RentalsMethod_method_id_01',
                            'LEFT',
                            [
                                'method_id',
                                '=',
                                'RentalsPayment_RentalsMethod_method_id_01.id',
                            ],
                        ],
                    ],
                    'having' => [],
                ],
                'expires_date' => NULL,
                'description' => NULL,
            ],
        ],
    ],
    [
        'name' => 'SavedSearch_Payments_SearchDisplay_Payments_Table08',
        'entity' => 'SearchDisplay',
        'cleanup' => 'unused',
        'update' => 'unmodified',
        'params' => [
            'version' => 4,
            'values' => [
                'name' => 'Payments_Table08',
                'label' => 'Payments',
                'saved_search_id.name' => 'Payments08',
                'type' => 'table',
                'settings' => [
                    'actions' => TRUE,
                    'limit' => 50,
                    'classes' => [
                        'table',
                        'table-striped',
                    ],
                    'pager' => [],
                    'placeholder' => 5,
                    'sort' => [
                        [
                            'id',
                            'ASC',
                        ],
                    ],
                    'columns' => [
                        [
                            'type' => 'field',
                            'key' => 'id',
                            'dataType' => 'Integer',
                            'label' => 'ID',
                            'sortable' => TRUE,
                        ],
                        [
                            'type' => 'field',
                            'key' => 'code',
                            'dataType' => 'String',
                            'label' => 'Receipt No',
                            'sortable' => TRUE,
                        ],
                        [
                            'type' => 'field',
                            'key' => 'RentalsPayment_Contact_tenant_id_01.display_name',
                            'dataType' => 'String',
                            'label' => 'Tenant',
                            'sortable' => TRUE,
                        ],
                        [
                            'type' => 'field',
                            'key' => 'RentalsPayment_RentalsMethod_method_id_01.name',
                            'dataType' => 'String',
                            'label' => 'Method',
                            'sortable' => TRUE,
                        ],
                        [
                            'type' => 'field',
                            'key' => 'amount',
                            'dataType' => 'Money',
                            'label' => 'Amount',
                            'sortable' => TRUE,
                        ],
                        [
                            'type' => 'field',
                            'key' => 'created_id.display_name',
                            'dataType' => 'String',
                            'label' => 'Created By',
                            'sortable' => TRUE,
                        ],
                        [
                            'type' => 'field',
                            'key' => 'created_date',
                            'dataType' => 'Timestamp',
                            'label' => 'Created Date',
                            'sortable' => TRUE,
                        ],
                        [
                            'type' => 'field',
                            'key' => 'modified_id.display_name',
                            'dataType' => 'String',
                            'label' => 'Modified By',
                            'sortable' => TRUE,
                        ],
                        [
                            'type' => 'field',
                            'key' => 'modified_date',
                            'dataType' => 'Timestamp',
                            'label' => 'Modified Date',
                            'sortable' => TRUE,
                        ],
                        [
                            'links' => [
                                [
                                    'entity' => '',
                                    'action' => '',
                                    'join' => '',
                                    'target' => 'crm-popup',
                                    'icon' => 'fa-eye',
                                    'text' => 'View',
                                    'style' => 'default',
                                    'path' => 'civicrm/rentals/payment?id=[id]&action=preview&reset=1',
                                    'condition' => [],
                                ],
                                [
                                    'entity' => '',
                                    'action' => '',
                                    'join' => '',
                                    'target' => 'crm-popup',
                                    'icon' => 'fa-pencil',
                                    'text' => 'Edit',
                                    'style' => 'default',
                                    'path' => 'civicrm/rentals/payment?id=[id]&action=update&reset=1',
                                    'condition' => [],
                                ],
                                [
                                    'entity' => '',
                                    'action' => '',
                                    'join' => '',
                                    'target' => 'crm-popup',
                                    'icon' => 'fa-trash-o',
                                    'text' => 'Delete',
                                    'style' => 'danger',
                                    'path' => 'civicrm/rentals/payment?id=[id]&action=delete&reset=1',
                                    'condition' => [],
                                ]
                            ],
                            'type' => 'links',
                            'alignment' => 'text-right',
                            'label' => 'Actions',
                        ],
                    ],
                ],
                'acl_bypass' => FALSE,
            ],
        ],
    ],
    [
        'name' => 'SavedSearch_Payments_SearchDisplay_Search_Payments_Table08',
        'entity' => 'SearchDisplay',
        'cleanup' => 'unused',
        'update' => 'unmodified',
        'params' => [
            'version' => 4,
            'values' => [
                'name' => 'Search_Payments_Table08',
                'label' => 'Payments',
                'saved_search_id.name' => 'Payments08',
                'type' => 'table',
                'settings' => [
                    'actions' => TRUE,
                    'limit' => 50,
                    'classes' => [
                        'table',
                        'table-striped',
                    ],
                    'pager' => [],
                    'placeholder' => 5,
                    'sort' => [
                        [
                            'id',
                            'ASC',
                        ],
                    ],
                    'columns' => [
                        [
                            'type' => 'field',
                            'key' => 'id',
                            'dataType' => 'Integer',
                            'label' => 'id',
                            'sortable' => TRUE,
                        ],
                        [
                            'type' => 'field',
                            'key' => 'code',
                            'dataType' => 'String',
                            'label' => 'Receipt No',
                            'sortable' => TRUE,
                        ],
                        [
                            'type' => 'field',
                            'key' => 'RentalsPayment_RentalsMethod_method_id_01.name',
                            'dataType' => 'String',
                            'label' => 'Method',
                            'sortable' => TRUE,
                        ],
                        [
                            'type' => 'field',
                            'key' => 'amount',
                            'dataType' => 'Money',
                            'label' => 'Amount',
                            'sortable' => TRUE,
                        ],
                        [
                            'type' => 'field',
                            'key' => 'created_id.display_name',
                            'dataType' => 'String',
                            'label' => 'Created By',
                            'sortable' => TRUE,
                        ],
                        [
                            'type' => 'field',
                            'key' => 'created_date',
                            'dataType' => 'Timestamp',
                            'label' => 'Created Date',
                            'sortable' => TRUE,
                        ],
                        [
                            'type' => 'field',
                            'key' => 'modified_id.display_name',
                            'dataType' => 'String',
                            'label' => 'Modified By',
                            'sortable' => TRUE,
                        ],
                        [
                            'type' => 'field',
                            'key' => 'modified_date',
                            'dataType' => 'Timestamp',
                            'label' => 'Modified Date',
                            'sortable' => TRUE,
                            'cssRules' => [],
                        ],
                        [
                            'links' => [
                                [
                                    'entity' => '',
                                    'action' => '',
                                    'join' => '',
                                    'target' => 'crm-popup',
                                    'icon' => 'fa-eye',
                                    'text' => 'View',
                                    'style' => 'default',
                                    'path' => 'civicrm/rentals/payment?id=[id]&action=preview&reset=1',
                                    'condition' => [],
                                ],
                                [
                                    'entity' => '',
                                    'action' => '',
                                    'join' => '',
                                    'target' => 'crm-popup',
                                    'icon' => 'fa-pencil',
                                    'text' => 'Edit',
                                    'style' => 'default',
                                    'path' => 'civicrm/rentals/payment?id=[id]&action=update&reset=1&cid=[RentalsPayment_Contact_tenant_id_01.id]',
                                    'condition' => [],
                                ],
                                [
                                    'entity' => '',
                                    'action' => '',
                                    'join' => '',
                                    'target' => 'crm-popup',
                                    'icon' => 'fa-trash-o',
                                    'text' => 'Delete',
                                    'style' => 'danger',
                                    'path' => 'civicrm/rentals/payment?id=[id]&action=delete&reset=1',
                                    'condition' => [],
                                ]
                            ],
                            'type' => 'links',
                            'alignment' => 'text-right',
                            'label' => 'Actions',
                        ],

                    ],
                ],
                'acl_bypass' => FALSE,
            ],
        ],
    ],
];