<?php
return [
    [
        'name' => 'SavedSearch_RentalsO8',
        'entity' => 'SavedSearch',
        'cleanup' => 'always',
        'update' => 'always',
        'params' => [
            'version' => 4,
            'values' => [
                'name' => 'RentalsO8',
                'label' => 'Rentals',
                'form_values' => NULL,
                'mapping_id' => NULL,
                'search_custom_id' => NULL,
                'api_entity' => 'RentalsRental',
                'api_params' => [
                    'version' => 4,
                    'select' => [
                        'id',
                        'code',
                        'RentalsRental_Contact_tenant_id_01.display_name',
                        'admission',
                        'discharge',
                    ],
                    'orderBy' => [],
                    'where' => [],
                    'groupBy' => [],
                    'join' => [
                        [
                            'Contact AS RentalsRental_Contact_tenant_id_01',
                            'LEFT',
                            [
                                'tenant_id',
                                '=',
                                'RentalsRental_Contact_tenant_id_01.id',
                            ],
                        ],
                    ],
                    'having' => [],
                ],
                'expires_date' => NULL,
                'description' => NULL,
            ],
        ],
    ],
    [
        'name' => 'SavedSearch_RentalsO8_SearchDisplay_All_Rentals_TableO8',
        'entity' => 'SearchDisplay',
        'cleanup' => 'always',
        'update' => 'always',
        'params' => [
            'version' => 4,
            'values' => [
                'name' => 'All_Rentals_TableO8',
                'label' => 'All Rentals Table',
                'saved_search_id.name' => 'RentalsO8',
                'type' => 'table',
                'settings' => [
                    'actions' => TRUE,
                    'limit' => 50,
                    'classes' => [
                        'table',
                        'table-striped',
                    ],
                    'pager' => [],
                    'placeholder' => 5,
                    'sort' => [],
                    'columns' => [
                        [
                            'type' => 'field',
                            'key' => 'id',
                            'dataType' => 'Integer',
                            'label' => 'Rental ID',
                            'sortable' => TRUE,
                        ],
                        [
                            'type' => 'field',
                            'key' => 'code',
                            'dataType' => 'String',
                            'label' => 'Code',
                            'sortable' => TRUE,
                        ],
                        [
                            'type' => 'field',
                            'key' => 'RentalsRental_Contact_tenant_id_01.display_name',
                            'dataType' => 'String',
                            'label' => 'Tenant',
                            'sortable' => TRUE,
                            'link' => [
                                'path' => '',
                                'entity' => 'Contact',
                                'action' => 'view',
                                'join' => 'RentalsRental_Contact_tenant_id_01',
                                'target' => '_blank',
                            ],
                            'title' => 'View Tenant',
                        ],
                        [
                            'type' => 'field',
                            'key' => 'admission',
                            'dataType' => 'Date',
                            'label' => 'Admission',
                            'sortable' => TRUE,
                        ],
                        [
                            'type' => 'field',
                            'key' => 'discharge',
                            'dataType' => 'Date',
                            'label' => 'Discharge',
                            'sortable' => TRUE,
                        ],
                        [
                            'links' => [
                                [
                                    'entity' => 'RentalsRental',
                                    'action' => 'update',
                                    'join' => '',
                                    'target' => 'crm-popup',
                                    'icon' => 'fa-pencil',
                                    'text' => 'View/Edit',
                                    'style' => 'default',
                                    'path' => '',
                                    'condition' => [],
                                ],
                            ],
                            'type' => 'links',
                            'alignment' => 'text-right',
                        ],
                    ],
                ],
                'acl_bypass' => TRUE,
            ],
        ],
    ],
    [
        'name' => 'SavedSearch_RentalsO8_SearchDisplay_Tenant_Rentals_Table08',
        'entity' => 'SearchDisplay',
        'cleanup' => 'always',
        'update' => 'always',
        'params' => [
            'version' => 4,
            'values' => [
                'name' => 'Tenant_Rentals_Table08',
                'label' => 'Tenant Rentals Table',
                'saved_search_id.name' => 'RentalsO8',
                'type' => 'table',
                'settings' => [
                    'actions' => TRUE,
                    'limit' => 50,
                    'classes' => [
                        'table',
                        'table-striped',
                    ],
                    'pager' => [],
                    'placeholder' => 5,
                    'sort' => [],
                    'columns' => [
                        [
                            'type' => 'field',
                            'key' => 'id',
                            'dataType' => 'Integer',
                            'label' => 'id',
                            'sortable' => TRUE,
                        ],
                        [
                            'type' => 'field',
                            'key' => 'code',
                            'dataType' => 'String',
                            'label' => 'Code',
                            'sortable' => TRUE,
                        ],
                        [
                            'type' => 'field',
                            'key' => 'admission',
                            'dataType' => 'Date',
                            'label' => 'Admission',
                            'sortable' => TRUE,
                        ],
                        [
                            'type' => 'field',
                            'key' => 'discharge',
                            'dataType' => 'Date',
                            'label' => 'Discharge',
                            'sortable' => TRUE,
                        ],
                        [
                            'links' => [
                                [
                                    'entity' => 'RentalsRental',
                                    'action' => 'update',
                                    'join' => '',
                                    'target' => 'crm-popup',
                                    'icon' => 'fa-pencil',
                                    'text' => 'Edit Rentals Rental',
                                    'style' => 'default',
                                    'path' => '',
                                    'condition' => [],
                                ],
                            ],
                            'type' => 'links',
                            'alignment' => 'text-right',
                            'label' => 'Actions',
                        ],
                    ],
                ],
                'acl_bypass' => FALSE,
            ],
        ],
    ],
];