-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_o8_rental`;
DROP TABLE IF EXISTS `civicrm_o8_rental_payment`;
DROP TABLE IF EXISTS `civicrm_o8_rental_invoice`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_o8_rental_invoice
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_o8_rental_invoice` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique Invoice ID',
  `contact_id` int unsigned COMMENT 'FK to Contact',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_o8_rental_invoice_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_o8_rental_payment
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_o8_rental_payment` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique Payment ID',
  `contact_id` int unsigned COMMENT 'FK to Contact',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_o8_rental_payment_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_o8_rental
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_o8_rental` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique Rental ID',
  `contact_id` int unsigned COMMENT 'FK to Contact',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_o8_rental_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;
