-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_o8_rental_payment`;
DROP TABLE IF EXISTS `civicrm_o8_rental_invoice`;
DROP TABLE IF EXISTS `civicrm_o8_rental_rental`;
DROP TABLE IF EXISTS `civicrm_o8_rental_method`;
DROP TABLE IF EXISTS `civicrm_o8_rental_expense`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_o8_rental_expense
-- *
-- * Rental Expense (Type)
-- *
-- *******************************************************/
CREATE TABLE `civicrm_o8_rental_expense` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique Rental Expense ID',
  `name` varchar(255) NOT NULL COMMENT 'Name',
  `frequency` varchar(25) NOT NULL DEFAULT "once_off",
  `is_refund` tinyint DEFAULT 0 COMMENT 'Is Refund?',
  `is_prorate` tinyint DEFAULT 1 COMMENT 'Is prorate?',
  `amount` decimal(20,2) NOT NULL COMMENT 'Amount',
  `created_id` int unsigned COMMENT 'FK to civicrm_contact, who created this',
  `created_date` datetime COMMENT 'Date and time this was created.',
  `modified_id` int unsigned COMMENT 'FK to civicrm_contact, who modified this',
  `modified_date` datetime COMMENT 'Date and time this was modified.',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index_name`(name),
  CONSTRAINT FK_civicrm_o8_rental_expense_created_id FOREIGN KEY (`created_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE SET NULL,
  CONSTRAINT FK_civicrm_o8_rental_expense_modified_id FOREIGN KEY (`modified_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE SET NULL
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_o8_rental_method
-- *
-- * Rental Payment Method
-- *
-- *******************************************************/
CREATE TABLE `civicrm_o8_rental_method` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique Rental Payment Method ID',
  `name` varchar(255) NOT NULL COMMENT 'Name',
  `created_id` int unsigned COMMENT 'FK to civicrm_contact, who created this',
  `created_date` datetime COMMENT 'Date and time this was created.',
  `modified_id` int unsigned COMMENT 'FK to civicrm_contact, who modified this',
  `modified_date` datetime COMMENT 'Date and time this was modified.',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index_name`(name),
  CONSTRAINT FK_civicrm_o8_rental_method_created_id FOREIGN KEY (`created_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE SET NULL,
  CONSTRAINT FK_civicrm_o8_rental_method_modified_id FOREIGN KEY (`modified_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE SET NULL
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_o8_rental_rental
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_o8_rental_rental` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique ID',
  `code` varchar(21) NULL DEFAULT NULL COMMENT 'Rental Code',
  `tenant_id` int unsigned COMMENT 'FK to Contact',
  `admission` date NOT NULL COMMENT 'Admission date',
  `discharge` date DEFAULT NULL COMMENT 'Discharge date',
  `created_id` int unsigned COMMENT 'FK to civicrm_contact, who created this',
  `created_date` datetime COMMENT 'Date and time this was created.',
  `modified_id` int unsigned COMMENT 'FK to civicrm_contact, who modified this',
  `modified_date` datetime COMMENT 'Date and time this was modified.',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index_code`(code),
  UNIQUE INDEX `idx_tenant_admission_discharge`(tenant_id, admission, discharge),
  CONSTRAINT FK_civicrm_o8_rental_rental_tenant_id FOREIGN KEY (`tenant_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE,
  CONSTRAINT FK_civicrm_o8_rental_rental_created_id FOREIGN KEY (`created_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE SET NULL,
  CONSTRAINT FK_civicrm_o8_rental_rental_modified_id FOREIGN KEY (`modified_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE SET NULL
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_o8_rental_invoice
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_o8_rental_invoice` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique RentalsInvoice ID',
  `code` varchar(12) COMMENT 'Code',
  `description` varchar(1255) NOT NULL COMMENT 'Name',
  `rental_id` int unsigned COMMENT 'FK to RentalsRental',
  `amount` decimal(20,2) NOT NULL COMMENT 'Amount',
  `start_date` date DEFAULT NULL COMMENT 'Invoice date',
  `end_date` date DEFAULT NULL COMMENT 'Invoice End Date',
  `created_id` int unsigned COMMENT 'FK to civicrm_contact, who created this',
  `created_date` datetime COMMENT 'Date and time this was created.',
  `modified_id` int unsigned COMMENT 'FK to civicrm_contact, who modified this',
  `modified_date` datetime COMMENT 'Date and time this was modified.',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index_code`(code),
  CONSTRAINT FK_civicrm_o8_rental_invoice_rental_id FOREIGN KEY (`rental_id`) REFERENCES `civicrm_o8_rental_rental`(`id`) ON DELETE SET NULL,
  CONSTRAINT FK_civicrm_o8_rental_invoice_created_id FOREIGN KEY (`created_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE SET NULL,
  CONSTRAINT FK_civicrm_o8_rental_invoice_modified_id FOREIGN KEY (`modified_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE SET NULL
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_o8_rental_payment
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_o8_rental_payment` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique RentalsPayment ID',
  `code` varchar(12) NULL DEFAULT NULL COMMENT 'Code',
  `tenant_id` int unsigned COMMENT 'FK to Contact',
  `method_id` int unsigned COMMENT 'FK to payment method',
  `amount` decimal(20,2) NOT NULL COMMENT 'Amount',
  `created_id` int unsigned COMMENT 'FK to civicrm_contact, who created this',
  `created_date` datetime COMMENT 'Date and time this was created.',
  `modified_id` int unsigned COMMENT 'FK to civicrm_contact, who modified this',
  `modified_date` datetime COMMENT 'Date and time this was modified.',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index_code`(code),
  CONSTRAINT FK_civicrm_o8_rental_payment_tenant_id FOREIGN KEY (`tenant_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE,
  CONSTRAINT FK_civicrm_o8_rental_payment_method_id FOREIGN KEY (`method_id`) REFERENCES `civicrm_o8_rental_method`(`id`) ON DELETE SET NULL,
  CONSTRAINT FK_civicrm_o8_rental_payment_created_id FOREIGN KEY (`created_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE SET NULL,
  CONSTRAINT FK_civicrm_o8_rental_payment_modified_id FOREIGN KEY (`modified_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE SET NULL
)
ENGINE=InnoDB;
